name: "Tests & Benchmarks"

permissions: { }

concurrency:
  group: tests-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - '**.txt'
      - '**.md'

env:
  GO_VERSION: "1.25"

jobs:
  prepare:
    name: "🔧 Prepare"
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1

      - uses: ./.github/actions/init-go
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: ./.github/actions/tidy-all-and-generate

      - name: 📦 Upload source
        uses: actions/upload-artifact@v7
        with:
          name: src-gen
          path: .

  test:
    name: "🧪 Test [${{ matrix.os }}]"
    needs: [ prepare ]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-15, windows-latest ]

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1

      - name: 📥 Download source
        uses: actions/download-artifact@v4
        with:
          name: src-gen
          path: .


      - uses: ./.github/actions/init-go
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: ./.github/actions/run-tests

  cross-build:
    name: "🛠️ Build [${{ matrix.goos }}/${{ matrix.goarch }}${{ matrix.goarm && format('/v{0}', matrix.goarm) || '' }}${{ matrix.gomips && format('/{0}', matrix.gomips) || '' }}]"
    needs: [ prepare ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - { goos: linux, goarch: amd64 }
          - { goos: linux, goarch: arm64 }
          - { goos: linux, goarch: arm, goarm: "7" }
          - { goos: linux, goarch: arm, goarm: "6" }
          - { goos: linux, goarch: "386" }
          - { goos: linux, goarch: riscv64 }
          - { goos: linux, goarch: mips64 }
          - { goos: linux, goarch: mips64le }
          - { goos: linux, goarch: mips, gomips: softfloat }
          - { goos: linux, goarch: mipsle, gomips: softfloat }
          - { goos: linux, goarch: ppc64 }
          - { goos: linux, goarch: ppc64le }
          - { goos: linux, goarch: s390x }
          # Windows
          - { goos: windows, goarch: amd64 }
          - { goos: windows, goarch: arm64 }
          - { goos: windows, goarch: "386" }
          # macOS
          - { goos: darwin, goarch: amd64 }
          - { goos: darwin, goarch: arm64 }
          # FreeBSD
          - { goos: freebsd, goarch: amd64 }
          - { goos: freebsd, goarch: arm64 }
          - { goos: freebsd, goarch: "386" }
          # OpenBSD
          - { goos: openbsd, goarch: amd64 }
          - { goos: openbsd, goarch: arm64 }
          # NetBSD
          - { goos: netbsd, goarch: amd64 }
          - { goos: netbsd, goarch: arm64 }

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1

      - name: 📥 Download source
        uses: actions/download-artifact@v4
        with:
          name: src-gen
          path: .


      - uses: ./.github/actions/init-go
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: ./.github/actions/cross-build-check
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goarm: ${{ matrix.goarm || '' }}
          gomips: ${{ matrix.gomips || '' }}
